site_name: Geraeteausleihe Microservice Semesterarbeit 4
site_description: Cloud Native Deployment mit Kubernetes und GitHub Actions
site_author: Efekan Demirci

theme:
  name: material
  language: de
  features:
    - toc.integrate
    - content.code.copy
    - navigation.instant
    - navigation.tracking

nav:
  - Start: index.md
  - Dokumentation: dokumentation.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - fenced_code
  - codehilite
  - tables
  - attr_list

extra_css:
  - extra.css

extra_javascript:
  - mermaid-force.js
