site_name: Geraeteausleihe Microservice Sem4
site_description: Cloud Native Deployment auf AWS mit Kubernetes, K3s auf EC2 und GitHub Actions
site_url: https://cancani.com/geraeteausleihe-sem4/

repo_url: https://github.com/Cancani/geraeteausleihe-sem4
repo_name: Cancani/geraeteausleihe-sem4

theme:
  name: windmill
  language: de

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-force.js

nav:
  - Start: index.md
  - Dokumentation: dokumentation.md
