apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geraeteausleihe
  namespace: geraeteausleihe
spec:
  ingressClassName: traefik
  rules:
    - host: geraeteausleihe.13.223.28.53.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geraeteausleihe
                port:
                  number: 80
